#!/bin/bash


while read l
do
	fName="test/"$(echo $l | awk '{print $1}')".ini"
	cp test.ini $fName
	nT=$(echo $l | awk '{print $2}')
	sed -i "s/\$ntrolleys/${nT}/g" $fName
	idT=$(echo $l | awk '{print $3}')
	sed -i "s/\$trolleysid/${idT}/g" $fName
	nSt1=$(echo $l | awk '{print $4}')
	sed -i "s/\$nslotsT1/${nSt1}/g" $fName
	idSt1=$(echo $l | awk '{print $5}')
	sed -i "s/\$slotsidT1/${idSt1}/g" $fName
	nSt3=$(echo $l | awk '{print $6}')
	sed -i "s/\$nslotsT3/${nSt3}/g" $fName
	idSt3=$(echo $l | awk '{print $7}')
	sed -i "s/\$slotsidT3/${idSt3}/g" $fName
	echo $fName $nT $idT $nSt1 $idSt1 $nSt3 $idSt3
done<Setup-detal-list.csv
